collections:
  news:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "layout_post"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "layout_news"

